### ISSUE TITLE
Get Number of Relevant Document per Search Query

### ISSUE THREAD

**Issue by nnistelrooij** [nnistelrooij/Information-Retrieval#18]
To compute the Mean Average Precision (MAP) measure, we need the number of relevant documents per search query. So I will make a function to get a Pandas DataFrame with the `queryid` and `numreldocs` from MonetDBLite and DuckDB.

**Comment by nnistelrooij** [comment]
See Pull Request #19. Added the `nr_relevant_documents()` function to the `Retriever` class that retrieves the number of relevant documents for each search query.

Search query 672 does not have any entries in the `qrels` table (and also not in the Robust04 relevance judgements file) and so the number of relevant documents, given query 672, is equal to 0. I guess just drop that query from the analysis, since you cannot divide by 0. Luckily, this will only increase the MAP.

**Comment by rusane** [comment]
I noticed that the term proximity weighted model (on its own) only retrieves the ranking of 182 queries compared to 243 queries that the other models (`okapi` and `kld`) retrieve, which is still less than the number of queries (250) in the test collection. 

Do you think it would be better for the evaluation to drop the queries for which any one of the models is not able to retrieve documents, or just mention it in the report?

**Comment by nnistelrooij** [comment]
I think you should include all (249 now) search queries in the computation of MAP. The fact that very few or no documents are ranked with TP was the reason I started thinking about including the pre-selection retrieval models. 

The MAP value for TP will likely drop drastically, as compared to the current score, but we want a fair comparison between the setups. Relevant documents are not retrieved at all for some search queries, so the Average Precision score should be 0 for such queries.

Definitely mention the 182 vs. 243 statistic in the limitations paragraph of the Discussion section.

**Comment by rusane** [comment]
Alright, I managed to calculate the MAP for the 249 queries by adding 'dummy' rows to the dataframe that represent the missing queries. TP did indeed drop quite a bit in MAP. The other models have a better MAP now after fixing the average precision metric but still quite low.

I also decided to compute P@k but I don't I think I will do that for all 249* queries because I would have to look for queries with less than `k` documents retrieved and then add up to `k` documents (with relevance of 0) for those queries, which seems a bit roundabout. Currently I filter out any queries with less than `k` documents retrieved (and of course all queries with no retrieved documents are not in there from the start) to compute P@k. I think I will just mention this, and that P@k might be inflated somewhat because the score is not taking into account queries without or less than `k` retrieved documents.

I'll soon push the new notebook (named `TestQueries.ipynb`) to the `TestQueries` branch so you can take a look at it if you want to. I'm only evaluating MonetDB currently by the way, I have not touched DuckDB yet but I have a feeling that running it will take very long relatively and I am not sure if I have time to do that (though code-wise we basically only have to replace `monet` for `duck` in the retriever calls).

*240 queries for all models except only TP, which has 153 queries

**Comment by nnistelrooij** [comment]
Great work! Maybe you can solve the P@k problems by looking at the comment I made on the commit I made the other comment on.

Running DuckDB is not a priority. We first need to get good data/numbers for MonetDBLite before we proceed with other parts of the project.

**Comment by rusane** [comment]
Your solution worked nicely ([commit](https://github.com/nnistelrooij/Information-Retrieval/commit/4ea0fc3887f43026095ed35f2b450ac92542c453)), I added a wrapper for P@k that implements your suggestion whenever the length of the ranked list of relevance judgement is smaller than *k*. So now P@k also is computed over all 249 queries, and as expected P@k for TP drops drastically.

**Comment by nnistelrooij** [comment]
Closing issue.
